#ifndef TEXTVIEWER_GLOBAL_H
#define TEXTVIEWER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXTVIEWER_LIBRARY)
#  define TEXTVIEWERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEXTVIEWERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEXTVIEWER_GLOBAL_H
